---
blank_issues_enabled: false
contact_links:
  - name: ğŸ“£ Announcements
    url: https://github.com/homelab-alpha/npm-workspaces-template/discussions/categories/announcements
    about: Stay updated with the latest news and announcements.
  - name: ğŸ¯ Feedback
    url: https://github.com/homelab-alpha/npm-workspaces-template/discussions/categories/feedback
    about: Share your suggestions and feedback to help us improve.
  - name: ğŸ’¬ General
    url: https://github.com/homelab-alpha/npm-workspaces-template/discussions/categories/general
    about: For general conversations that don't fit into another category.
  - name: ğŸ’¡ Ideas
    url: https://github.com/homelab-alpha/npm-workspaces-template/discussions/categories/ideas
    about: Share your ideas for new features and improvements.
  - name: ğŸ—³ï¸ Polls
    url: https://github.com/homelab-alpha/npm-workspaces-template/discussions/categories/polls
    about: Participate in polls and give your opinion.
  - name: ğŸ™ Q&A
    url: https://github.com/homelab-alpha/npm-workspaces-template/discussions/categories/q-a
    about: Ask specific questions and get answers from the community.
